"""DBSP resolution/velocity table for H-alpha, H-beta, H-gamma.

Computes linear dispersion, FWHM, R, and Delta-v for the Palomar
Double Spectrograph using the 1200/7100 grating (red, H-alpha) and
1200/5000 grating (blue, H-beta and H-gamma) over a set of slit
widths. Slit-limited resolution is assumed (slit > seeing).

Grating/camera parameters from the pyraf-dbsp source
(https://github.com/ebellm/pyraf-dbsp/blob/master/dbsp.py).
Empirical FWHM(1") anchor values are user-tunable at the top of
the script -- verify against arc-line FWHM in your data.

Generated by Claude Opus 4.7 on June 3 2026.
"""
from dataclasses import dataclass
import numpy as np
from astropy import constants as const
from astropy import units as u

# -- Empirical anchors: FWHM at 1" slit in each arm. ---------------
# Update these if you measure them from your arc frames.
FWHM_1ARCSEC = {"red": 2.0 * u.AA, "blue": 1.7 * u.AA}

# -- Pixel sizes (post-upgrade). -----------------------------------
PIX_UM = {"red": 15.0 * u.micron, "blue": 15.0 * u.micron}

# Slit widths to tabulate (arcsec).
SLITS_ARCSEC = np.array([0.5, 1.0, 1.5, 2.0, 4.0]) * u.arcsec


@dataclass
class ArmConfig:
    """Parameters for one DBSP arm.

    Generated by Claude Opus 4.7 on June 3 2026.

    Attributes:
        name: 'red' or 'blue'.
        grating_lpmm: Groove density (lines/mm).
        beta_deg: Diffraction angle (deg).
        f_cam_mm: Camera focal length (mm).
        order: Grating order.
    """
    name: str
    grating_lpmm: float
    beta_deg: float
    f_cam_mm: float
    order: int = 1


# pyraf-dbsp values: red f_cam = 12", blue = 9";
# red beta = 35 deg, blue = 38.5 deg.
ARM_RED = ArmConfig("red", 1200, 35.0, 12 * 25.4)
ARM_BLUE = ArmConfig("blue", 1200, 38.5, 9 * 25.4)


def linear_dispersion(arm: ArmConfig) -> u.Quantity:
    """Linear dispersion d(lambda)/dx at the detector.

    Generated by Claude Opus 4.7 on June 3 2026.

    Args:
        arm: ArmConfig with grating + camera parameters.

    Returns:
        Linear dispersion in Angstrom / mm.
    """
    d_groove = (1.0 / arm.grating_lpmm) * u.mm
    beta = np.deg2rad(arm.beta_deg)
    f_cam = arm.f_cam_mm * u.mm
    disp = d_groove * np.cos(beta) / (arm.order * f_cam)
    return disp.to(u.AA / u.mm)


def fwhm_at_slit(arm_name: str,
                 slit: u.Quantity) -> u.Quantity:
    """Slit-limited FWHM scaled from the 1" anchor value.

    Generated by Claude Opus 4.7 on June 3 2026.

    Args:
        arm_name: 'red' or 'blue'.
        slit: Slit width with arcsec units.

    Returns:
        FWHM in Angstrom.
    """
    return FWHM_1ARCSEC[arm_name] * (slit / (1.0 * u.arcsec))


def print_table(line_name: str,
                wavelength: u.Quantity,
                arm: ArmConfig) -> None:
    """Print dispersion/R/dv table for one line over slit widths.

    Generated by Claude Opus 4.7 on June 3 2026.

    Args:
        line_name: Display name (e.g., 'H-alpha').
        wavelength: Rest wavelength of the line.
        arm: ArmConfig for the relevant arm.
    """
    disp_mm = linear_dispersion(arm)
    pix = PIX_UM[arm.name].to(u.mm)
    disp_pix = (disp_mm * pix).to(u.AA)
    c_kms = const.c.to(u.km / u.s)

    print(f"\n{line_name} ({wavelength.to(u.AA).value:.1f} A) "
          f"- DBSP {arm.name} arm, 1200/"
          f"{'7100' if arm.name == 'red' else '5000'}")
    print(f"  Grating: {arm.grating_lpmm} l/mm, "
          f"beta={arm.beta_deg} deg, "
          f"f_cam={arm.f_cam_mm:.1f} mm")
    print(f"  Dispersion: {disp_mm.value:.2f} A/mm "
          f"= {disp_pix.value:.3f} A/pix "
          f"({PIX_UM[arm.name].value:.0f} um pix)")
    print()
    print(f"  {'slit':>6} {'FWHM':>8} {'N_pix/res':>10} "
          f"{'R':>7} {'dv [km/s]':>10}")
    print(f"  {'-'*6} {'-'*8} {'-'*10} {'-'*7} {'-'*10}")
    for slit in SLITS_ARCSEC:
        fwhm = fwhm_at_slit(arm.name, slit)
        n_pix = (fwhm / disp_pix).to(u.dimensionless_unscaled)
        R = (wavelength / fwhm).to(u.dimensionless_unscaled)
        dv = (c_kms / R).to(u.km / u.s)
        print(f"  {slit.value:>5.2f}\" "
              f"{fwhm.value:>7.2f} A "
              f"{n_pix.value:>10.1f} "
              f"{R.value:>7.0f} "
              f"{dv.value:>10.1f}")


def main() -> None:
    """Print resolution tables for H-alpha, H-beta, H-gamma.

    Generated by Claude Opus 4.7 on June 3 2026.
    """
    lines = [
        ("H-alpha", 6562.8 * u.AA, ARM_RED),
        ("H-beta", 4861.3 * u.AA, ARM_BLUE),
        ("H-gamma", 4340.5 * u.AA, ARM_BLUE),
    ]
    for name, wl, arm in lines:
        print_table(name, wl, arm)


if __name__ == "__main__":
    main()
