"""
Driver for the dip-depth extinction-law (beta) fits.

Fits three models to the multi-band dip-depth dataset (single power law
with shared beta; single power law with independent per-star beta; and a
broken power law with a free breakpoint), compares them by Delta-BIC,
and writes the money plot, per-model QA plots, and the beta-violin plot.

Usage:
    python drivers/run_beta_fit.py [options]

    (interactive by default: prompts for row exclusions)

Options:
    --defaults          Use default exclusions; no prompt.
    --include-all       No exclusions.
    --exclude "i,j,k"   Explicit exclusion set (row_ids).
    --refit             Ignore the fit cache and resample.
    --outdir PATH       Override the output directory.

Generated by Claude Code on 2026-06-21.
"""
import argparse
import json
import logging
import os
import sys
from os.path import join
from typing import List, Optional, Sequence

import pandas as pd

from complexrotators import fit_dips_beta as fdb

try:
    from complexrotators.paths import RESULTSDIR, DATADIR
except ImportError:  # pragma: no cover - paths module is expected
    RESULTSDIR = join(os.path.dirname(__file__), "..", "results")
    DATADIR = join(os.path.dirname(__file__), "..", "data")

CSV_PATH = join(
    os.path.dirname(__file__), "..", "papers", "Bouma_2026_cgcd",
    "tables", "dipdepths_thiswork_and_literature.csv",
)
SVO_DIR = join(DATADIR, "photometry", "svo_bandpasses")

logging.basicConfig(
    level=logging.INFO, format="%(levelname)s %(name)s: %(message)s"
)
LOG = logging.getLogger("run_beta_fit")


def default_excluded_row_ids(df_all: pd.DataFrame) -> List[int]:
    """Row ids of the three low-S/N TESS measurements of TIC 262400835.

    Generated by Claude Code on 2026-06-21.

    Args:
        df_all: The full table with a ``row_id`` column.

    Returns:
        Sorted list of default-excluded row ids.
    """
    mask = (df_all["star"] == "TIC 262400835") & (df_all["band"] == "TESS")
    return sorted(int(r) for r in df_all.loc[mask, "row_id"])


def print_row_table(df_all: pd.DataFrame, excluded: Sequence[int]) -> None:
    """Print all rows with a marker on currently-excluded ones.

    Generated by Claude Code on 2026-06-21.

    Args:
        df_all: The full table with a ``row_id`` column.
        excluded: Currently-excluded row ids.
    """
    excl = set(int(e) for e in excluded)
    print("\n row_id  X  star                date_ut                  "
          "band     depth%")
    print(" " + "-" * 74)
    for r in df_all.itertuples():
        mark = "x" if r.row_id in excl else " "
        print(f"  {r.row_id:4d}   {mark}  {r.star:<18.18s} "
              f"{r.date_ut:<22.22s} {r.band:<8.8s} {r.depth_pct:>5.2f}")
    print()


def resolve_exclusions(
    df_all: pd.DataFrame, args: argparse.Namespace
) -> List[int]:
    """Determine the excluded row ids from flags or interactive prompt.

    Generated by Claude Code on 2026-06-21.

    Args:
        df_all: The full table with a ``row_id`` column.
        args: Parsed CLI arguments.

    Returns:
        Sorted list of excluded row ids.
    """
    defaults = default_excluded_row_ids(df_all)

    if args.include_all:
        return []
    if args.exclude is not None:
        return sorted(int(x) for x in args.exclude.split(",") if x.strip())
    if args.defaults:
        return defaults

    # Interactive mode.
    print_row_table(df_all, defaults)
    print(f"Default exclusions (low-S/N TESS of TIC 262400835): {defaults}")
    resp = input(
        "[Enter]/Y = accept defaults, n = include everything, "
        "or comma-separated row_ids to toggle: "
    ).strip()

    if resp == "" or resp.lower() == "y":
        return defaults
    if resp.lower() == "n":
        return []

    toggled = set(defaults)
    for tok in resp.split(","):
        tok = tok.strip()
        if not tok:
            continue
        rid = int(tok)
        toggled.symmetric_difference_update({rid})
    return sorted(toggled)


def main(argv: Optional[Sequence[str]] = None) -> int:
    """Run the three beta fits and write all outputs.

    Generated by Claude Code on 2026-06-21.

    Args:
        argv: Optional argument vector (defaults to sys.argv).

    Returns:
        Process exit code.
    """
    p = argparse.ArgumentParser(description="dip-depth beta fits")
    p.add_argument("--defaults", action="store_true",
                   help="use default exclusions, no prompt")
    p.add_argument("--include-all", action="store_true",
                   help="no exclusions")
    p.add_argument("--exclude", type=str, default=None,
                   help='explicit exclusion set, e.g. "4,9,13"')
    p.add_argument("--refit", action="store_true",
                   help="ignore cache and resample")
    p.add_argument("--outdir", type=str, default=None,
                   help="override output directory")
    args = p.parse_args(argv)

    outdir_base = args.outdir or join(RESULTSDIR, "beta_fit")

    df_all = fdb.load_depths(CSV_PATH)
    excluded = resolve_exclusions(df_all, args)

    df = fdb.load_depths(CSV_PATH, exclude_row_ids=excluded)
    data = fdb.prepare_arrays(df, SVO_DIR)

    print(f"\nIncluded measurements : {data['n']}")
    print(f"Epochs / stars        : {data['N_e']} / {data['N_s']}")
    print(f"Excluded row_ids      : {excluded}\n")

    # Run two variants: one that fits an intrinsic-scatter term and one
    # that does not (the latter lets chi^2 expose model misfit directly).
    # The no-sigma_int variant floors the depth error at 0.1% so a few
    # sub-0.1% literature errors do not dominate the fit.
    variants = [
        (True, 0.0, "with_sigma_int"),
        (False, 0.1, "no_sigma_int"),
    ]
    for fit_si, floor_pct, sub in variants:
        cfg = dict(fdb.DEFAULT_CFG)
        cfg["fit_sigma_int"] = fit_si
        cfg["depth_err_floor_pct"] = floor_pct
        vdata = fdb.apply_err_floor(data, floor_pct)
        outdir = join(outdir_base, sub)
        run_variant(vdata, cfg, outdir, excluded, refit=args.refit)

    return 0


def run_variant(
    data: dict, cfg: dict, outdir: str, excluded: Sequence[int],
    refit: bool = False,
) -> None:
    """Fit all three models for one sigma_int choice and write outputs.

    Generated by Claude Code on 2026-06-21.

    Args:
        data: Output of prepare_arrays.
        cfg: Sampler/model config (its ``fit_sigma_int`` flag selects
            the variant).
        outdir: Output directory for this variant.
        excluded: Excluded row_ids (recorded in run_config.json).
        refit: If True, ignore the fit cache and resample.
    """
    fit_si = cfg.get("fit_sigma_int", True)
    cache_dir = join(outdir, "cache")
    os.makedirs(cache_dir, exist_ok=True)

    tag = "WITH sigma_int" if fit_si else "NO sigma_int (sigma = s)"
    key = fdb._cache_key("shared", data, cfg)
    print(f"\n########## Variant: {tag} ##########")
    print(f"Output dir   : {outdir}")
    print(f"Cache key    : {key[:16]}")

    idatas = {}
    for name in ("shared", "perstar", "broken"):
        LOG.info("[%s] fitting model: %s", tag, name)
        idatas[name] = fdb.get_or_fit(
            name, data, cfg, cache_dir, refit=refit
        )

    # Model comparison (Delta-BIC).
    rows = [fdb.compute_bic(name, idatas[name], data, cfg)
            for name in ("shared", "perstar", "broken")]
    bic_df = pd.DataFrame(rows)
    bic_df["dBIC"] = bic_df["BIC"] - bic_df["BIC"].min()
    bic_df.to_csv(join(outdir, "bic_comparison.csv"), index=False)

    print("\n=== Model comparison (Delta-BIC) ===")
    cols = ["model", "k", "dof", "sigma_int", "chi2red_meas_err",
            "chi2red_incl_sigma_int", "BIC", "dBIC"]
    print(bic_df[cols].to_string(
        index=False, float_format=lambda v: f"{v:.2f}"))
    if fit_si:
        print("chi2red_incl_sigma_int ~1 by construction; "
              "chi2red_meas_err shows residual misfit vs measurement "
              "error alone.")
    else:
        print("sigma_int not fitted: chi2red_meas_err == "
              "chi2red_incl_sigma_int is the true goodness of fit.")
    print("Reading: dBIC > 10 => strong preference for the lower-BIC "
          "model.\n")

    # Figures.
    fdb.plot_money(idatas, data, join(outdir, "money_plot_beta.pdf"),
                   fit_sigma_int=fit_si)
    for name in ("shared", "perstar", "broken"):
        fdb.plot_qa(name, idatas[name], join(outdir, f"qa_{name}.pdf"))
    fdb.plot_beta_violins(
        idatas["shared"], idatas["perstar"], data,
        join(outdir, "beta_violins.pdf"),
    )

    best = bic_df.loc[bic_df["BIC"].idxmin(), "model"]
    beta_ci = fdb._ci68(fdb._flat(idatas["shared"], "beta"))
    print(f"SUMMARY [{tag}]: best model = {best}; shared beta = "
          f"{beta_ci['med']:.2f} "
          f"(+{beta_ci['hi']-beta_ci['med']:.2f} "
          f"-{beta_ci['med']-beta_ci['lo']:.2f}); outputs in {outdir}")

    with open(join(outdir, "run_config.json"), "w") as f:
        json.dump(
            {"excluded_row_ids": list(excluded), "cfg": cfg,
             "n": data["n"], "N_e": data["N_e"], "N_s": data["N_s"]},
            f, indent=2,
        )


if __name__ == "__main__":
    sys.exit(main())
