"""
Render the measured dip depths into the "This work" rows of manuscript Table 3
("Dip depths by bandpass", tab:dipdepths in papers/Bouma_2026_cgcd/ms.tex).

We write ONLY the data rows of the \\cutinhead{This work} block, in the exact
column format of that table:

    Star & Date (UT) & Band & $\\delta$ (\\%) & Ref. \\\\

i.e. the only measured quantity written is the depth and its uncertainty,
$\\delta\\pm\\sigma_\\delta$, to two decimals.  No FWHM column.  Rows are emitted
in the manuscript's hand-curated order (the per-star band ordering is not
alphabetical, so it is encoded explicitly in THIS_WORK below); a dataset that
is not yet fitted prints an $X.XX\\pm X.XX$ placeholder, so the block always has
the same shape as the inline table.  When a phase-folded `_pm2cycle` variant of
a dataset exists and is done, its (better-constrained) depth is used in place of
the single-cycle fit.

The rows are injected DIRECTLY into ms.tex, between the sentinel comments

    % BEGIN fit-dips rows ...
    % END fit-dips rows

(just inside \\cutinhead{This work}).  We do NOT \\input an external file:
AASTeX's deluxetable captures everything between \\startdata and \\enddata as a
token list and replays it, and a file read during that replay (\\input or even
the \\@@input primitive) derails the alignment with a "Misplaced \\noalign"
error.  In-place injection sidesteps that entirely.  The Literature rows below
the markers are hand-kept in ms.tex and are never touched.

Run:  python -m fit_dips.make_table   (from apps/fit-dips/)
"""
import os

from . import registry

MS_TEX = os.path.abspath(os.path.join(
    registry.DATASETS_DIR, "..", "..", "..", "papers", "Bouma_2026_cgcd",
    "ms.tex"))

BEGIN_MARK = ("% BEGIN fit-dips rows -- auto-generated by "
              "`python -m fit_dips.make_table`; do not edit by hand.")
END_MARK = "% END fit-dips rows"

PLACEHOLDER = r"$X.XX\pm X.XX$"

# Photometric bands rendered in math italics; everything else (TESS, Tierras,
# NB2.09) stays upright text.
_MATH_BANDS = {"g", "r", "i", "z", "B"}

# The "This work" block, in manuscript order. Each group is
#   (star_display, date_display, id_prefix, [band keys in display order])
# where the dataset id for a band is f"{id_prefix}_{band}".
THIS_WORK = [
    (r"TIC\,262400835", "2020 Dec 13", "TIC262400835_20201213",
     ["g", "r", "i", "z", "TESS"]),
    (r"TIC\,262400835", "2020 Dec 15", "TIC262400835_20201215",
     ["g", "r", "i", "z", "TESS"]),
    (r"TIC\,262400835", "2020 Dec 16", "TIC262400835_20201216",
     ["g", "r", "z", "TESS"]),
    (r"LP\,12-502", "2023 Dec 08", "LP12-502_20231208",
     ["B", "g", "TESS"]),
    (r"LP\,12-502", "2023 Dec 15", "LP12-502_20231215",
     ["B", "g", "Tierras", "TESS"]),
    (r"TIC\,300651846", "2025 Feb 10", "TIC300651846_20250210",
     ["TESS", "NB2.09"]),
]

# Column widths, chosen to line up with the inline table in ms.tex.
_W_STAR, _W_DATE, _W_BAND, _W_DEPTH = 14, 11, 8, 14


def _band_display(band):
    return f"${band}$" if band in _MATH_BANDS else band


def _resolve_id(dataset_id):
    """Prefer a done phase-folded `_pm2cycle` variant over the single-cycle base."""
    variant = f"{dataset_id}_pm2cycle"
    if registry.exists(variant) and \
            registry.load(variant).get("status") == registry.STATUS_DONE:
        return variant
    return dataset_id


def _depths(dataset_id):
    """Return a list of $\\delta\\pm\\sigma$ strings (2 dp), one per fitted dip.

    Falls back to a single placeholder if the dataset is missing, not done, or
    has no preferred-model dips.
    """
    rid = _resolve_id(dataset_id)
    if not registry.exists(rid):
        return [PLACEHOLDER]
    rec = registry.load(rid)
    pref = rec.get("preferred_model")
    if rec.get("status") != registry.STATUS_DONE or not pref \
            or pref not in rec.get("fits", {}):
        return [PLACEHOLDER]
    dips = rec["fits"][pref].get("dips", [])
    if not dips:
        return [PLACEHOLDER]
    return [f"${d['delta_pct']:.2f}\\pm {d['delta_pct_err']:.2f}$"
            for d in dips]


def build_rows():
    """Return the list of fully-formatted LaTeX row strings (no trailing \\n)."""
    rows = []
    for star, date, prefix, bands in THIS_WORK:
        first = True  # show star/date only on the first row of the group
        for band in bands:
            for depth in _depths(f"{prefix}_{band}"):
                s = star if first else ""
                d = date if first else ""
                rows.append(
                    f"{s:<{_W_STAR}} & {d:<{_W_DATE}} & "
                    f"{_band_display(band):<{_W_BAND}} & "
                    f"{depth:<{_W_DEPTH}} & 1 \\\\")
                first = False
    return rows


def render():
    """Inject the generated rows into ms.tex between the sentinel markers."""
    rows = build_rows()
    with open(MS_TEX) as f:
        lines = f.read().split("\n")

    begins = [i for i, ln in enumerate(lines) if ln.strip() == BEGIN_MARK.strip()]
    ends = [i for i, ln in enumerate(lines) if ln.strip() == END_MARK.strip()]
    if len(begins) != 1 or len(ends) != 1 or ends[0] <= begins[0]:
        raise RuntimeError(
            f"expected exactly one BEGIN and one (later) END marker in "
            f"{MS_TEX}; found BEGIN at {begins}, END at {ends}. Add:\n"
            f"  {BEGIN_MARK}\n  {END_MARK}\n"
            f"just inside \\cutinhead{{This work}}.")

    new_lines = lines[:begins[0] + 1] + rows + lines[ends[0]:]
    with open(MS_TEX, "w") as f:
        f.write("\n".join(new_lines))
    return MS_TEX, len(rows)


if __name__ == "__main__":
    path, n = render()
    print(f"injected {n} \"This work\" dip row(s) into {path}")
