"""
Fit the wavelength dependence of complex-rotator dip depths,
delta proportional to lambda^(-beta), across a heterogeneous multi-band
dataset.  The per-(star, epoch) amplitude is absorbed into a free
intercept so the slope(s) beta are fit directly, with no per-epoch
reference band.

Three models are implemented and compared via Delta-BIC:
  Model 1 (shared)  : single power law, beta shared across all stars.
  Model 2 (perstar) : single power law, independent beta per star.
  Model 3 (broken)  : broken power law (shared) with a free breakpoint
                      wavelength near ~1 micron, softplus-smoothed hinge.

Implementation notes (environment is pymc 6.0.1 + arviz 1.2.0):
  - pm.sample returns an xarray DataTree (not arviz.InferenceData).
  - NetCDF caching uses idata.to_netcdf(path, engine="netcdf4").
  - Posterior variables are read via idata.posterior.dataset[name].
  - 68% credible intervals are computed from draws (np.percentile),
    since az.summary now defaults to an 89% ETI.

Contents:
  load_depths
  get_lambda_eff
  prepare_arrays
  build_model_shared
  build_model_perstar
  build_model_broken
  build_model
  get_or_fit
  compute_bic
  plot_money
  plot_qa
  plot_beta_violins

Generated by Claude Code on 2026-06-21.
"""
import hashlib
import json
import logging
import os
from os.path import join
from typing import Dict, List, Optional, Sequence

import arviz as az
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
from matplotlib.lines import Line2D
import numpy as np
import pandas as pd
import pymc as pm
from aesthetic.plot import set_style
from astropy import units as u

LOG = logging.getLogger(__name__)

# Display/gauge wavelength for intercepts and money-plot normalization.
LAMBDA0_MICRON: float = 1.0

# Fixed softplus smoothing scale (dex) for the broken-law hinge.
KAPPA_DEFAULT: float = 0.05

# Bump this whenever priors change; it feeds the cache key so stale
# fits are not silently reused.
PRIORS_VERSION: str = "v1"

# Default sampler / model configuration.
DEFAULT_CFG: Dict = {
    "chains": 4,
    "tune": 2000,
    "draws": 2000,
    "target_accept": 0.90,
    "seed": 42,
    "kappa": KAPPA_DEFAULT,
    "priors_version": PRIORS_VERSION,
    # If False, models do NOT fit an intrinsic-scatter term: the
    # likelihood uses the measurement error alone (sigma = s).  Then the
    # chi^2 directly exposes whether the power law actually describes the
    # data, rather than letting sigma_int absorb the misfit.
    "fit_sigma_int": True,
    # Floor on the depth error (percentage points) applied before the
    # fit (see apply_err_floor).  0.0 disables it; the no-sigma_int
    # variant uses 0.1 to cap unrealistically small literature errors.
    "depth_err_floor_pct": 0.0,
}

# Nominal effective wavelengths (micron), used only as a fallback when a
# named SVO profile cannot be read.  TESS and I+z are broad/composite
# bands whose nominal values are the crudest (see brief Section 4).
NOMINAL_LAMBDA_EFF: Dict[str, float] = {
    "g": 0.475, "g'": 0.475,
    "r": 0.622, "r'": 0.622,
    "R": 0.658,
    "i": 0.760,
    "I": 0.806, "I_C": 0.806,
    "Tierras": 0.864,
    "z": 0.905, "z'": 0.905, "z_s": 0.905,
    "I+z": 0.860,
    "TESS": 0.800,
    "NB2.09": 2.090,
    "J": 1.235,
    "H": 1.662,
    "K_s": 2.159,
}


def load_depths(
    csv_path: str, exclude_row_ids: Optional[Sequence[int]] = None
) -> pd.DataFrame:
    """Load the dip-depth table and drop excluded rows.

    Assigns a stable integer ``row_id`` (the original CSV row order)
    before any filtering, so exclusion sets are reproducible.  Adds the
    grouping unit ``epoch = (star, date_ut)`` and the log-depth columns
    ``y = log10(depth_pct)`` and ``s = depth_err_pct/(depth_pct*ln10)``.

    Generated by Claude Code on 2026-06-21.

    Args:
        csv_path: Path to dipdepths_thiswork_and_literature.csv.
        exclude_row_ids: ``row_id`` values to drop before indexing.

    Returns:
        DataFrame with row_id, epoch, y, s columns added; excluded rows
        removed; index reset.
    """
    df = pd.read_csv(csv_path)
    df["row_id"] = np.arange(len(df), dtype=int)

    if exclude_row_ids:
        exclude = set(int(r) for r in exclude_row_ids)
        df = df[~df["row_id"].isin(exclude)].copy()

    df["epoch"] = df["star"].astype(str) + " | " + df["date_ut"].astype(str)
    df["y"] = np.log10(df["depth_pct"].to_numpy(float))
    df["s"] = df["depth_err_pct"].to_numpy(float) / (
        df["depth_pct"].to_numpy(float) * np.log(10.0)
    )

    return df.reset_index(drop=True)


def _read_svo_profile(path: str) -> Dict[str, np.ndarray]:
    """Read a two-column SVO ASCII profile (wavelength[AA], transmission).

    Generated by Claude Code on 2026-06-21.

    Args:
        path: Path to the SVO ``.dat`` transmission file.

    Returns:
        Dict with ``wave_aa`` and ``trans`` arrays.
    """
    arr = np.genfromtxt(path)
    wave_aa = np.asarray(arr[:, 0], dtype=float)
    trans = np.asarray(arr[:, 1], dtype=float)
    return {"wave_aa": wave_aa, "trans": trans}


def _pivot_wavelength_micron(
    wave_aa: np.ndarray, trans: np.ndarray
) -> float:
    """Pivot wavelength sqrt(int T*lam dlam / int T/lam dlam), in micron.

    The pivot wavelength is source-independent, which is what we want
    for a slope in log lambda.

    Generated by Claude Code on 2026-06-21.

    Args:
        wave_aa: Wavelength grid (Angstrom).
        trans: Transmission on that grid.

    Returns:
        Pivot wavelength in micron.
    """
    num = np.trapezoid(trans * wave_aa, wave_aa)
    den = np.trapezoid(trans / wave_aa, wave_aa)
    lam_aa = np.sqrt(num / den)
    return float((lam_aa * u.AA).to(u.micron).value)


def _tophat_pivot_micron(center_nm: float, fwhm_nm: float) -> float:
    """Pivot wavelength of a top-hat bandpass, in micron.

    Generated by Claude Code on 2026-06-21.

    Args:
        center_nm: Top-hat center (nm).
        fwhm_nm: Top-hat full width (nm).

    Returns:
        Pivot wavelength in micron.
    """
    lo = (center_nm - fwhm_nm / 2.0) * 10.0
    hi = (center_nm + fwhm_nm / 2.0) * 10.0
    wave_aa = np.linspace(lo, hi, 1001)
    trans = np.ones_like(wave_aa)
    return _pivot_wavelength_micron(wave_aa, trans)


def get_lambda_eff(
    svo_filter: str, svo_dir: str, band: Optional[str] = None
) -> u.Quantity:
    """Resolve the effective (pivot) wavelength for one measurement.

    ``svo_filter`` is the per-row profile specifier from the CSV; it is
    resolved per (star, epoch, band) by the table generator, never by
    the bare band string (the same band string maps to different
    physical filters across rows).  Supported forms:
      - ``"<file>.dat"``                : single SVO profile.
      - ``"<fileA>+<fileB>"``           : composite; transmissions are
        co-added on a common grid (e.g. PTFO I+z).  Flagged approximate.
      - ``"TOPHAT:<center_nm>:<fwhm_nm>"``: synthesized top-hat (Tierras).
    Falls back to NOMINAL_LAMBDA_EFF[band] with a warning if a profile
    cannot be read.  Kept swappable for later SED weighting.

    Generated by Claude Code on 2026-06-21.

    Args:
        svo_filter: Per-row SVO profile specifier.
        svo_dir: Directory of SVO ``.dat`` transmission curves.
        band: Band string, used only for the nominal fallback / warning.

    Returns:
        Effective wavelength as an astropy Quantity (micron).
    """
    spec = str(svo_filter).strip()

    try:
        if spec.upper().startswith("TOPHAT:"):
            _, center_nm, fwhm_nm = spec.split(":")
            lam = _tophat_pivot_micron(float(center_nm), float(fwhm_nm))
            return lam * u.micron

        if "+" in spec:
            # Composite band: co-add transmissions on a common grid.
            files = spec.split("+")
            profs = [
                _read_svo_profile(join(svo_dir, f.strip())) for f in files
            ]
            lo = max(p["wave_aa"].min() for p in profs)
            hi = min(p["wave_aa"].max() for p in profs)
            if not (hi > lo):
                # Disjoint support: union grid, zero-fill outside each.
                lo = min(p["wave_aa"].min() for p in profs)
                hi = max(p["wave_aa"].max() for p in profs)
            grid = np.linspace(lo, hi, 2000)
            trans = np.zeros_like(grid)
            for p in profs:
                trans += np.interp(
                    grid, p["wave_aa"], p["trans"], left=0.0, right=0.0
                )
            LOG.warning(
                "Composite band %s: lambda_eff is approximate.", spec
            )
            return _pivot_wavelength_micron(grid, trans) * u.micron

        prof = _read_svo_profile(join(svo_dir, spec))
        return _pivot_wavelength_micron(prof["wave_aa"], prof["trans"]) * (
            u.micron
        )

    except (OSError, ValueError) as exc:
        key = band if band is not None else spec
        if key in NOMINAL_LAMBDA_EFF:
            LOG.warning(
                "Profile '%s' unreadable (%s); using nominal lambda_eff "
                "for band '%s'.", spec, exc, key
            )
            return NOMINAL_LAMBDA_EFF[key] * u.micron
        raise


def prepare_arrays(df: pd.DataFrame, svo_dir: str) -> Dict:
    """Build the numeric arrays and index maps the models consume.

    Effective wavelengths are resolved per row from ``svo_filter``.
    Epochs and stars are integer-indexed.  ``delta = log10(lam/lambda0)``
    with lambda0 = 1 micron; since lambda0 == 1, delta == log10(lam).

    Generated by Claude Code on 2026-06-21.

    Args:
        df: Output of load_depths (already filtered).
        svo_dir: Directory of SVO transmission curves.

    Returns:
        Dict of arrays/metadata: y, s, epoch_idx, star_idx, lam_micron,
        delta, loglam, n, N_e, N_s, ybar, epoch_labels, star_names,
        bands, df.
    """
    df = df.reset_index(drop=True)

    star_names: List[str] = list(pd.unique(df["star"]))
    star_to_idx = {s: i for i, s in enumerate(star_names)}

    epoch_labels: List[str] = list(pd.unique(df["epoch"]))
    epoch_to_idx = {e: i for i, e in enumerate(epoch_labels)}

    star_idx = df["star"].map(star_to_idx).to_numpy(int)
    epoch_idx = df["epoch"].map(epoch_to_idx).to_numpy(int)

    lam_micron = np.array(
        [
            get_lambda_eff(sf, svo_dir, band=b).to(u.micron).value
            for sf, b in zip(df["svo_filter"], df["band"])
        ],
        dtype=float,
    )
    loglam = np.log10(lam_micron)
    delta = np.log10(lam_micron / LAMBDA0_MICRON)

    y = df["y"].to_numpy(float)
    s = df["s"].to_numpy(float)

    # Warn (do not crash) on epochs left with a single band: they
    # constrain their intercept but carry no slope information.
    counts = df.groupby("epoch").size()
    for ep, n_band in counts.items():
        if n_band < 2:
            LOG.warning(
                "Epoch '%s' has a single band; no slope information.", ep
            )

    return {
        "y": y,
        "s": s,
        "epoch_idx": epoch_idx,
        "star_idx": star_idx,
        "lam_micron": lam_micron,
        "delta": delta,
        "loglam": loglam,
        "n": int(len(df)),
        "N_e": int(len(epoch_labels)),
        "N_s": int(len(star_names)),
        "ybar": float(np.mean(y)),
        "epoch_labels": epoch_labels,
        "star_names": star_names,
        "bands": list(df["band"]),
        "df": df,
    }


def apply_err_floor(data: Dict, floor_pct: float) -> Dict:
    """Return a copy of ``data`` with a floor on the depth-error column.

    Floors ``depth_err_pct`` at ``floor_pct`` (percentage points of
    depth) before recomputing the log10-depth error
    ``s = depth_err_pct / (depth_pct * ln 10)``.  Used for the
    no-intrinsic-scatter variant, where a few literature points have
    sub-0.1% formal errors that would otherwise dominate the fit; the
    floor enforces a realistic measurement-precision limit.

    Generated by Claude Code on 2026-06-21.

    Args:
        data: Output of prepare_arrays.
        floor_pct: Minimum depth error in percentage points (<= 0 is a
            no-op).

    Returns:
        A shallow copy of ``data`` with an updated ``s`` array (other
        keys, including ``df``, are shared unchanged).
    """
    if floor_pct <= 0:
        return data
    out = dict(data)
    depth = data["df"]["depth_pct"].to_numpy(float)
    err = data["df"]["depth_err_pct"].to_numpy(float)
    err_floored = np.maximum(err, floor_pct)
    out["s"] = err_floored / (depth * np.log(10.0))
    n_floored = int(np.sum(err < floor_pct))
    if n_floored:
        LOG.info("Applied %.2f%% depth-error floor to %d/%d rows.",
                 floor_pct, n_floored, len(err))
    return out


def _obs_sigma(data: Dict, fit_sigma_int: bool):
    """Likelihood sigma: measurement error, optionally plus sigma_int.

    Generated by Claude Code on 2026-06-21.

    Args:
        data: Output of prepare_arrays.
        fit_sigma_int: If True, add a HalfNormal(0.10) intrinsic-scatter
            term in quadrature; if False, return the measurement error
            alone (no sigma_int parameter is created).

    Returns:
        The per-measurement sigma (a tensor if fit_sigma_int, else the
        numeric measurement-error array).
    """
    if not fit_sigma_int:
        return data["s"]
    sigma_int = pm.HalfNormal("sigma_int", sigma=0.10)
    return pm.math.sqrt(data["s"] ** 2 + sigma_int ** 2)


def build_model_shared(data: Dict, fit_sigma_int: bool = True) -> pm.Model:
    """Model 1: single power law, beta shared across all stars.

    mu_eb = c_e - beta * delta_b.

    Generated by Claude Code on 2026-06-21.

    Args:
        data: Output of prepare_arrays.
        fit_sigma_int: Whether to fit an intrinsic-scatter term.

    Returns:
        A pm.Model.
    """
    with pm.Model() as model:
        c = pm.Normal(
            "c_e", mu=data["ybar"], sigma=1.0, shape=data["N_e"]
        )
        beta = pm.Normal("beta", mu=0.0, sigma=3.0)
        mu = c[data["epoch_idx"]] - beta * data["delta"]
        sigma = _obs_sigma(data, fit_sigma_int)
        pm.Normal("obs", mu=mu, sigma=sigma, observed=data["y"])
    return model


def build_model_perstar(data: Dict, fit_sigma_int: bool = True) -> pm.Model:
    """Model 2: single power law, independent beta per star (no pooling).

    mu_eb = c_e - beta_{s(e)} * delta_b.

    Generated by Claude Code on 2026-06-21.

    Args:
        data: Output of prepare_arrays.
        fit_sigma_int: Whether to fit an intrinsic-scatter term.

    Returns:
        A pm.Model.
    """
    with pm.Model() as model:
        c = pm.Normal(
            "c_e", mu=data["ybar"], sigma=1.0, shape=data["N_e"]
        )
        beta_s = pm.Normal(
            "beta_s", mu=0.0, sigma=3.0, shape=data["N_s"]
        )
        mu = c[data["epoch_idx"]] - beta_s[data["star_idx"]] * data["delta"]
        sigma = _obs_sigma(data, fit_sigma_int)
        pm.Normal("obs", mu=mu, sigma=sigma, observed=data["y"])
    return model


def build_model_broken(
    data: Dict, kappa: float = KAPPA_DEFAULT,
    fit_sigma_int: bool = True,
) -> pm.Model:
    """Model 3: broken power law (shared) with a free breakpoint.

    With w_b = log10(lam_b / lam_break) and a softplus-smoothed hinge
    h_b = kappa * softplus(w_b / kappa) ~ max(w_b, 0):

        mu_eb = c_e - beta1 * w_b + (beta1 - beta2) * h_b

    Here c_e is the depth at lam_break; the gauge floats with the
    breakpoint and the intercept absorbs it.  ``kappa`` is fixed (not a
    fitted parameter).  lam_break is sampled in log lambda over
    Uniform(0.70, 1.60) micron.

    Generated by Claude Code on 2026-06-21.

    Args:
        data: Output of prepare_arrays.
        kappa: Fixed softplus smoothing scale (dex).
        fit_sigma_int: Whether to fit an intrinsic-scatter term.

    Returns:
        A pm.Model.
    """
    log_lo, log_hi = np.log10(0.70), np.log10(1.60)
    with pm.Model() as model:
        c = pm.Normal(
            "c_e", mu=data["ybar"], sigma=1.0, shape=data["N_e"]
        )
        beta1 = pm.Normal("beta1", mu=0.0, sigma=3.0)
        beta2 = pm.Normal("beta2", mu=0.0, sigma=3.0)
        log_lam_break = pm.Uniform(
            "log_lam_break", lower=log_lo, upper=log_hi
        )
        pm.Deterministic("lam_break", 10.0 ** log_lam_break)

        # loglam is a numeric constant; w is an RV through log_lam_break.
        w = data["loglam"] - log_lam_break
        h = kappa * pm.math.softplus(w / kappa)
        mu = c[data["epoch_idx"]] - beta1 * w + (beta1 - beta2) * h
        sigma = _obs_sigma(data, fit_sigma_int)
        pm.Normal("obs", mu=mu, sigma=sigma, observed=data["y"])
    return model


# Population-level parameters per model (for QA plots and counting).
POP_PARAMS: Dict[str, List[str]] = {
    "shared": ["beta", "sigma_int"],
    "perstar": ["beta_s", "sigma_int"],
    "broken": ["beta1", "beta2", "lam_break", "sigma_int"],
}


def build_model(model_name: str, data: Dict, cfg: Dict) -> pm.Model:
    """Dispatch to the named model builder.

    Generated by Claude Code on 2026-06-21.

    Args:
        model_name: One of "shared", "perstar", "broken".
        data: Output of prepare_arrays.
        cfg: Sampler/model config (provides kappa for the broken model).

    Returns:
        A pm.Model.
    """
    fit_si = cfg.get("fit_sigma_int", True)
    if model_name == "shared":
        return build_model_shared(data, fit_sigma_int=fit_si)
    if model_name == "perstar":
        return build_model_perstar(data, fit_sigma_int=fit_si)
    if model_name == "broken":
        return build_model_broken(
            data, kappa=cfg.get("kappa", KAPPA_DEFAULT),
            fit_sigma_int=fit_si,
        )
    raise ValueError(f"unknown model_name: {model_name}")


def _cache_key(model_name: str, data: Dict, cfg: Dict) -> str:
    """SHA-256 over the data subset, lambda_eff, model, and sampler cfg.

    Generated by Claude Code on 2026-06-21.

    Args:
        model_name: Model identifier.
        data: Output of prepare_arrays.
        cfg: Sampler/model config.

    Returns:
        Hex digest string.
    """
    df = data["df"]
    rows = sorted(
        f"{r.star},{r.date_ut},{r.band},{r.depth_pct},{r.depth_err_pct}"
        for r in df.itertuples()
    )
    lam = [round(float(v), 6) for v in data["lam_micron"]]
    payload = {
        "model": model_name,
        "rows": rows,
        "lambda_eff": sorted(lam),
        "cfg": {
            "chains": cfg["chains"],
            "tune": cfg["tune"],
            "draws": cfg["draws"],
            "target_accept": cfg["target_accept"],
            "seed": cfg["seed"],
            "kappa": cfg["kappa"],
            "priors_version": cfg["priors_version"],
            "fit_sigma_int": cfg.get("fit_sigma_int", True),
            "depth_err_floor_pct": cfg.get("depth_err_floor_pct", 0.0),
        },
    }
    canon = json.dumps(payload, sort_keys=True)
    return hashlib.sha256(canon.encode("utf-8")).hexdigest()


def get_or_fit(
    model_name: str,
    data: Dict,
    cfg: Dict,
    cache_dir: str,
    refit: bool = False,
):
    """Sample (or load from cache) one model, returning InferenceData.

    The cache key is a SHA-256 of the included rows, the lambda_eff
    actually used, the model name, and the sampler config.  Cache files
    are ``<cache_dir>/<model_name>_<key[:16]>.nc`` (NetCDF).

    Generated by Claude Code on 2026-06-21.

    Args:
        model_name: One of "shared", "perstar", "broken".
        data: Output of prepare_arrays.
        cfg: Sampler/model config.
        cache_dir: Directory for NetCDF cache files.
        refit: If True, ignore any cached fit and resample.

    Returns:
        The fit as an arviz/xarray DataTree (InferenceData-like).
    """
    os.makedirs(cache_dir, exist_ok=True)
    key = _cache_key(model_name, data, cfg)
    path = join(cache_dir, f"{model_name}_{key[:16]}.nc")

    if os.path.exists(path) and not refit:
        LOG.info("Loading cached fit: %s", path)
        return az.from_netcdf(path)

    target_accept = cfg["target_accept"]
    if model_name == "broken":
        target_accept = max(target_accept, 0.95)

    model = build_model(model_name, data, cfg)
    with model:
        idata = pm.sample(
            draws=cfg["draws"],
            tune=cfg["tune"],
            chains=cfg["chains"],
            target_accept=target_accept,
            random_seed=cfg["seed"],
            progressbar=True,
            idata_kwargs={"log_likelihood": True},
        )
    idata.to_netcdf(path, engine="netcdf4")
    LOG.info("Wrote fit cache: %s", path)
    return idata


# Free-parameter counts k for BIC.  c_e contributes N_e to every model,
# so Delta-BIC is driven by the slope structure (kappa is fixed).  The
# intrinsic-scatter term adds one parameter only when it is fitted.
def _k_params(
    model_name: str, data: Dict, fit_sigma_int: bool = True
) -> int:
    """Free-parameter count for BIC.

    Generated by Claude Code on 2026-06-21.

    Args:
        model_name: Model identifier.
        data: Output of prepare_arrays.
        fit_sigma_int: Whether the intrinsic-scatter term is fitted.

    Returns:
        Number of free parameters k.
    """
    n_e, n_s = data["N_e"], data["N_s"]
    n_sig = 1 if fit_sigma_int else 0
    if model_name == "shared":
        return n_e + 1 + n_sig           # c_e + beta [+ sigma_int]
    if model_name == "perstar":
        return n_e + n_s + n_sig         # c_e + beta_s [+ sigma_int]
    if model_name == "broken":
        return n_e + 2 + 1 + n_sig       # c_e + beta1,2 + lam_break [+sig]
    raise ValueError(f"unknown model_name: {model_name}")


def _draw_max_loglik(idata) -> float:
    """Max over posterior draws of the summed pointwise log-likelihood.

    Generated by Claude Code on 2026-06-21.

    Args:
        idata: Fit with a ``log_likelihood`` group.

    Returns:
        The maximum per-draw total observed log-likelihood.
    """
    ll = idata.log_likelihood.dataset["obs"]
    obs_dims = [d for d in ll.dims if d not in ("chain", "draw")]
    total = ll.sum(dim=obs_dims)
    return float(np.asarray(total).max())


def _sigma_int_median(idata) -> float:
    """Median intrinsic scatter, or 0.0 if the model did not fit it.

    Generated by Claude Code on 2026-06-21.

    Args:
        idata: A fit.

    Returns:
        Posterior-median sigma_int (dex), or 0.0 when absent.
    """
    if "sigma_int" in idata.posterior.dataset:
        return _median_scalar(idata, "sigma_int")
    return 0.0


def _median_prediction(model_name: str, idata, data: Dict):
    """Posterior-median model prediction mu and intrinsic scatter.

    Generated by Claude Code on 2026-06-21.

    Args:
        model_name: One of "shared", "perstar", "broken".
        idata: The corresponding fit.
        data: Output of prepare_arrays.

    Returns:
        Tuple (mu, sigma_int): mu is the per-measurement median model
        prediction in log10-depth; sigma_int is the median intrinsic
        scatter (dex), or 0.0 if the model did not fit it.
    """
    ei = data["epoch_idx"]
    c_med = _median_vector(idata, "c_e")
    sigma_int = _sigma_int_median(idata)

    if model_name == "shared":
        beta = _median_scalar(idata, "beta")
        mu = c_med[ei] - beta * data["delta"]
    elif model_name == "perstar":
        beta_s = _median_vector(idata, "beta_s")
        mu = c_med[ei] - beta_s[data["star_idx"]] * data["delta"]
    elif model_name == "broken":
        b1 = _median_scalar(idata, "beta1")
        b2 = _median_scalar(idata, "beta2")
        lam_break = _median_scalar(idata, "lam_break")
        w = data["loglam"] - np.log10(lam_break)
        h = KAPPA_DEFAULT * np.logaddexp(0.0, w / KAPPA_DEFAULT)
        mu = c_med[ei] - b1 * w + (b1 - b2) * h
    else:
        raise ValueError(f"unknown model_name: {model_name}")
    return mu, sigma_int


def compute_bic(model_name: str, idata, data: Dict, cfg: Dict) -> Dict:
    """Compute BIC and reduced chi^2 diagnostics for one model.

    BIC = k*ln(n) - 2*lnL_max, with ``lnL_max`` the maximized
    observed-data log-likelihood evaluated at the MAP (matching the
    standard BIC definition and the draw-based cross-check, rather than
    the full model logp which would fold in prior densities).  If
    find_MAP fails, falls back to the draw-based maximum and flags it.

    Two reduced chi^2 are reported, both from the posterior-median fit
    (dof = n - k):
      - ``chi2red_meas_err``: denominator is the measurement error
        only; far above 1 because the reported dip-depth errors are
        small relative to the real epoch/star scatter (this measures
        unmodeled scatter, not slope quality).
      - ``chi2red_incl_sigma_int``: denominator adds the fitted
        intrinsic scatter in quadrature; ~1 by construction, since
        sigma_int absorbs the excess variance.

    Generated by Claude Code on 2026-06-21.

    Args:
        model_name: One of "shared", "perstar", "broken".
        idata: The corresponding fit (with log_likelihood group).
        data: Output of prepare_arrays.
        cfg: Sampler/model config.

    Returns:
        Dict with model, k, n, dof, sigma_int, lnL_max, lnL_draw_max,
        BIC, chi2_meas_err, chi2red_meas_err, chi2_incl_sigma_int,
        chi2red_incl_sigma_int, used_map.
    """
    n = data["n"]
    k = _k_params(model_name, data, cfg.get("fit_sigma_int", True))
    dof = n - k
    lnl_draw = _draw_max_loglik(idata)

    y, s = data["y"], data["s"]
    mu, sigma_int = _median_prediction(model_name, idata, data)
    chi2_meas = float(np.sum((y - mu) ** 2 / s ** 2))
    chi2_tot = float(np.sum((y - mu) ** 2 / (s ** 2 + sigma_int ** 2)))

    lnl_map = np.nan
    used_map = False
    try:
        model = build_model(model_name, data, cfg)
        with model:
            mp = pm.find_MAP(progressbar=False)
            pt = {v.name: mp[v.name] for v in model.value_vars}
            obs_logp = model.compile_logp(vars=[model["obs"]], sum=True)
            lnl_map = float(obs_logp(pt))
        if np.isfinite(lnl_map):
            used_map = True
    except Exception as exc:  # noqa: BLE001 - fall back robustly
        LOG.warning("find_MAP failed for %s (%s); using draw max.",
                    model_name, exc)

    lnl_max = lnl_map if used_map else lnl_draw
    bic = k * np.log(n) - 2.0 * lnl_max

    return {
        "model": model_name,
        "k": k,
        "n": n,
        "dof": dof,
        "sigma_int": sigma_int,
        "lnL_max": lnl_max,
        "lnL_draw_max": lnl_draw,
        "BIC": bic,
        "chi2_meas_err": chi2_meas,
        "chi2red_meas_err": chi2_meas / dof,
        "chi2_incl_sigma_int": chi2_tot,
        "chi2red_incl_sigma_int": chi2_tot / dof,
        "used_map": used_map,
    }


def _ci68(samples: np.ndarray) -> Dict[str, float]:
    """16/50/84 percentiles of a flat draw array.

    Generated by Claude Code on 2026-06-21.

    Args:
        samples: 1-D array of posterior draws.

    Returns:
        Dict with lo, med, hi.
    """
    lo, med, hi = np.percentile(np.asarray(samples).ravel(), [16, 50, 84])
    return {"lo": float(lo), "med": float(med), "hi": float(hi)}


def _fmt_ci(ci: Dict[str, float], prec: int = 2) -> str:
    """LaTeX ``med^{+hi}_{-lo}`` string for a 68% CI (no $ delimiters).

    Generated by Claude Code on 2026-06-21.

    Args:
        ci: Dict with lo, med, hi (output of _ci68).
        prec: Decimal places.

    Returns:
        LaTeX-formatted asymmetric-uncertainty string.
    """
    med, lo, hi = ci["med"], ci["lo"], ci["hi"]
    return (f"{med:.{prec}f}^{{+{hi - med:.{prec}f}}}"
            f"_{{-{med - lo:.{prec}f}}}")


def _flat(idata, name: str) -> np.ndarray:
    """Flatten posterior draws of a scalar variable to 1-D.

    Generated by Claude Code on 2026-06-21.

    Args:
        idata: A fit.
        name: Variable name in the posterior group.

    Returns:
        1-D array of draws.
    """
    return np.asarray(idata.posterior.dataset[name]).ravel()


# Per-star marker cycle for the money plot (stable ordering).  Markers
# are drawn white-filled with black edges so the figure prints clearly
# in black and white; the shape alone distinguishes the star.
_STAR_MARKERS = ["o", "s", "^", "D", "v", "P", "X", "*"]


def _median_scalar(idata, name: str) -> float:
    """Posterior median of a scalar variable.

    Generated by Claude Code on 2026-06-21.

    Args:
        idata: A fit.
        name: Variable name in the posterior group.

    Returns:
        The posterior median.
    """
    return float(np.median(_flat(idata, name)))


def _median_vector(idata, name: str) -> np.ndarray:
    """Per-element posterior median of a vector variable.

    Generated by Claude Code on 2026-06-21.

    Args:
        idata: A fit.
        name: Vector variable name (last axis indexes the elements).

    Returns:
        1-D array of element-wise posterior medians.
    """
    a = np.asarray(idata.posterior.dataset[name])
    return np.median(a.reshape(-1, a.shape[-1]), axis=0)


def plot_money(
    idatas: Dict, data: Dict, outpath: str, fit_sigma_int: bool = True
) -> None:
    """Money plot: delta/delta0 vs lambda_eff with Model 1 and Model 3.

    Data points are normalized per epoch by delta0,e = 10^median(c_e)
    from Model 1 (the depth at lambda0 = 1 micron).  Model 1 (shared PL)
    and Model 3 (broken PL) posterior-median curves and 68% credible
    bands are overlaid, each normalized to 1 at lambda0.  The residual
    panel shows (data - model) standardized by the same sigma the model
    used: sqrt(s^2 + sigma_int^2) when the intrinsic scatter is fitted,
    or the measurement error s alone when it is not.

    Generated by Claude Code on 2026-06-21.

    Args:
        idatas: Dict with keys "shared" and "broken".
        data: Output of prepare_arrays.
        outpath: Output PDF path.
        fit_sigma_int: Whether the fits included sigma_int; only sets the
            residual-axis label (the denominators are read from each
            fit, so they are correct regardless).
    """
    set_style("science")
    fig, axes = plt.subplots(
        2, 2, figsize=(8, 4.8), sharex=True, sharey="row",
        gridspec_kw={"height_ratios": [3, 1], "hspace": 0.06,
                     "wspace": 0.05},
    )
    (ax_s, ax_b), (axr_s, axr_b) = axes

    shared = idatas["shared"]
    broken = idatas["broken"]

    # Per-epoch normalization from Model 1 intercepts (same data in both
    # columns; only the overlaid model differs).
    c_med = _median_vector(shared, "c_e")  # (N_e,), log-depth at lambda0
    delta0 = 10.0 ** c_med  # depth at lambda0, per epoch

    df = data["df"]
    epoch_idx = data["epoch_idx"]
    lam = data["lam_micron"]
    depth = df["depth_pct"].to_numpy(float)
    star_idx = data["star_idx"]

    # Error bars use the (possibly floored) log-depth error from data so
    # the displayed uncertainties match what the fit assumed:
    # ratio_err / ratio = depth_err / depth = s * ln(10).
    ratio = depth / delta0[epoch_idx]
    ratio_err = ratio * data["s"] * np.log(10.0)

    lam_grid = np.linspace(lam.min() * 0.9, lam.max() * 1.05, 200)
    lg = np.log10(lam_grid)  # = delta on the grid (lambda0 = 1)

    # Single power law (left): ratio(lam) = lam^{-beta}, gauged to 1.
    beta = _flat(shared, "beta")
    m1 = 10.0 ** (-np.outer(beta, lg))  # (ndraw, ngrid)
    _band(ax_s, lam_grid, m1, "C0", "Single power-law")

    # Broken power law (right): ratio = 10^{f(lam) - f(lambda0)},
    # f(lam) = -beta1*w + (beta1-beta2)*kappa*softplus(w/kappa).
    b1 = _flat(broken, "beta1")
    b2 = _flat(broken, "beta2")
    lam_break = _flat(broken, "lam_break")
    kappa = KAPPA_DEFAULT
    m3 = _broken_ratio(lam_grid, b1, b2, lam_break, kappa)
    _band(ax_b, lam_grid, m3, "C3", "Broken power-law")

    # Dashed outer bands widen the mean relation by sigma_int, showing
    # where individual measurements should fall (only when sigma_int is
    # fit; it is 0 in the no-intrinsic-scatter variant).
    if fit_sigma_int:
        _predictive_band(ax_s, lam_grid, m1, _flat(shared, "sigma_int"),
                         "C0", seed=0)
        _predictive_band(ax_b, lam_grid, m3, _flat(broken, "sigma_int"),
                         "C3", seed=1)

    # Data overplotted on both columns, in a black-and-white marker
    # scheme (white fill, black edge; shape distinguishes the star).
    def _plot_data(axp) -> None:
        for si in range(data["N_s"]):
            m = star_idx == si
            if not np.any(m):
                continue
            axp.errorbar(
                lam[m], ratio[m], yerr=ratio_err[m], ls="none",
                marker=_STAR_MARKERS[si % len(_STAR_MARKERS)],
                markerfacecolor="white", markeredgecolor="black",
                markeredgewidth=0.8, color="black", ecolor="black",
                markersize=6, elinewidth=0.8, capsize=1.5, zorder=5,
            )
    _plot_data(ax_s)
    _plot_data(ax_b)

    # Per-column parameter annotations (68% credible intervals).  The
    # solid band is the credible interval on the MEAN relation; the
    # dashed band additionally includes sigma_int.
    b1c = _ci68(beta)
    txt_s = r"$\beta = " + _fmt_ci(b1c) + "$"
    c1, c2, cb = _ci68(b1), _ci68(b2), _ci68(lam_break)
    txt_b = (
        r"$\beta_1 = " + _fmt_ci(c1) + "$\n"
        r"$\beta_2 = " + _fmt_ci(c2) + "$\n"
        r"$\lambda_b = " + _fmt_ci(cb) + r"\,\mu$m"
    )
    if fit_sigma_int:
        txt_s += ("\n" + r"$\sigma_{\rm int} = "
                  + f"{_sigma_int_median(shared):.2f}$ dex")
        txt_b += ("\n" + r"$\sigma_{\rm int} = "
                  + f"{_sigma_int_median(broken):.2f}$ dex")
    ax_s.text(0.04, 0.04, txt_s, transform=ax_s.transAxes, fontsize=7,
              va="bottom", ha="left")
    ax_b.text(0.04, 0.04, txt_b, transform=ax_b.transAxes, fontsize=7,
              va="bottom", ha="left")

    # Top-row cosmetics.  sharey="row" keeps the two columns on a common
    # y-scale; set the limits once from the data (with error bars).
    ax_s.set_title("Single power-law", fontsize=9)
    ax_b.set_title("Broken power-law", fontsize=9)
    for axp in (ax_s, ax_b):
        axp.set_xscale("log")
        axp.set_yscale("log")
        axp.set_yticks([0.4, 0.6, 1, 2, 3])
        axp.yaxis.set_major_formatter(mticker.ScalarFormatter())
        axp.yaxis.set_minor_formatter(mticker.NullFormatter())
    ax_s.set_ylabel(r"$\delta / \delta_{1\,\mu\mathrm{m}}$")
    ax_s.set_ylim((ratio - ratio_err).min() / 1.25,
                  (ratio + ratio_err).max() * 1.25)

    # Star-shape legend (plus a predictive-band proxy), drawn once.
    star_handles = [
        Line2D([0], [0], ls="none",
               marker=_STAR_MARKERS[i % len(_STAR_MARKERS)],
               markerfacecolor="white", markeredgecolor="black",
               markersize=6, label=data["star_names"][i])
        for i in range(data["N_s"])
    ]
    if fit_sigma_int:
        star_handles.append(Line2D(
            [0], [0], color="gray", ls="--", lw=1.0,
            label=r"$68\%$ incl. $\sigma_{\rm int}$"))
    ax_b.legend(handles=star_handles, fontsize=6, loc="upper right")

    # Residual panels: standardized residuals for the column's model
    # only (left = single, right = broken).  Each uses its model's own
    # sigma (sigma_int is 0 when not fitted).
    y, s = data["y"], data["s"]
    mu1, sig1 = _median_prediction("shared", shared, data)
    mu3, sig3 = _median_prediction("broken", broken, data)
    res1 = (y - mu1) / np.sqrt(s ** 2 + sig1 ** 2)
    res3 = (y - mu3) / np.sqrt(s ** 2 + sig3 ** 2)

    def _plot_resid(axrp, res: np.ndarray, color: str) -> None:
        for si in range(data["N_s"]):
            m = star_idx == si
            if not np.any(m):
                continue
            axrp.scatter(lam[m], res[m],
                         marker=_STAR_MARKERS[si % len(_STAR_MARKERS)],
                         s=26, facecolors=color, edgecolors="black",
                         linewidths=0.6, alpha=0.70, zorder=4)
        axrp.axhline(0.0, color="gray", lw=0.8, zorder=1)
        for yy in (-1.0, 1.0):
            axrp.axhline(yy, color="gray", lw=0.5, ls=":", zorder=1)
    _plot_resid(axr_s, res1, "C0")
    _plot_resid(axr_b, res3, "C3")

    # Matched residual y-limits across the two columns (sharey="row").
    ymax = 1.15 * np.nanmax(np.abs(np.concatenate([res1, res3])))
    axr_s.set_ylim(-ymax, ymax)
    if fit_sigma_int:
        rlabel = r"$(\delta - {\rm mod})/\sqrt{s^2+\sigma_{\rm int}^2}$"
    else:
        rlabel = r"$(\delta - {\rm mod})/s$"
    axr_s.set_ylabel(rlabel, fontsize=8)
    for axrp in (axr_s, axr_b):
        axrp.set_xlabel(r"$\lambda_{\rm eff}$ [$\mu$m]")
        axrp.set_xticks([0.4, 0.6, 1, 2])
        axrp.xaxis.set_major_formatter(mticker.ScalarFormatter())
        axrp.xaxis.set_minor_formatter(mticker.NullFormatter())

    fig.savefig(outpath, bbox_inches="tight")
    plt.close(fig)


def _broken_ratio(
    lam_grid: np.ndarray,
    b1: np.ndarray,
    b2: np.ndarray,
    lam_break: np.ndarray,
    kappa: float,
) -> np.ndarray:
    """Model-3 delta/delta0 over draws, normalized to 1 at lambda0.

    Generated by Claude Code on 2026-06-21.

    Args:
        lam_grid: Wavelength grid (micron).
        b1: beta1 draws.
        b2: beta2 draws.
        lam_break: lam_break draws (micron).
        kappa: Fixed smoothing scale.

    Returns:
        Array (ndraw, ngrid) of delta/delta0.
    """
    def soft(x: np.ndarray) -> np.ndarray:
        return np.logaddexp(0.0, x)

    lg = np.log10(lam_grid)[None, :]            # (1, ngrid)
    lb = np.log10(lam_break)[:, None]           # (ndraw, 1)
    b1 = b1[:, None]
    b2 = b2[:, None]

    def f(w: np.ndarray) -> np.ndarray:
        return -b1 * w + (b1 - b2) * kappa * soft(w / kappa)

    w = lg - lb
    w0 = (np.log10(LAMBDA0_MICRON) - lb)
    return 10.0 ** (f(w) - f(w0))


def _band(
    ax, x: np.ndarray, draws: np.ndarray, color: str, label: str
) -> None:
    """Overlay a posterior-median curve and 68% credible band.

    Generated by Claude Code on 2026-06-21.

    Args:
        ax: Matplotlib axis.
        x: x grid.
        draws: Array (ndraw, len(x)) of curve draws.
        color: Line/band color.
        label: Legend label for the median curve.
    """
    lo, med, hi = np.percentile(draws, [16, 50, 84], axis=0)
    ax.plot(x, med, color=color, lw=1.6, label=label, zorder=4)
    ax.fill_between(x, lo, hi, color=color, alpha=0.20, zorder=2)


def _predictive_band(
    ax, x: np.ndarray, ratio_draws: np.ndarray,
    sigma_int_draws: np.ndarray, color: str, seed: int = 0,
) -> None:
    """Overlay a dashed 68% posterior-predictive band.

    Widens the mean-relation draws by each draw's intrinsic scatter
    sigma_int (added as Gaussian noise in log10 space), so the band
    shows where individual measurements are expected to fall -- i.e. it
    reflects the model's intrinsic variability, unlike the narrower
    credible band on the mean relation drawn by ``_band``.

    Generated by Claude Code on 2026-06-21.

    Args:
        ax: Matplotlib axis.
        x: x grid.
        ratio_draws: Array (ndraw, len(x)) of mean delta/delta0 draws.
        sigma_int_draws: (ndraw,) intrinsic-scatter draws (dex), aligned
            with ratio_draws.
        color: Band color.
        seed: RNG seed for the predictive noise (reproducibility).
    """
    g = np.log10(ratio_draws)
    rng = np.random.default_rng(seed)
    noise = rng.standard_normal(g.shape) * np.asarray(sigma_int_draws)[:, None]
    pred = 10.0 ** (g + noise)
    lo, hi = np.percentile(pred, [16, 84], axis=0)
    ax.plot(x, lo, color=color, ls="--", lw=1.0, alpha=0.7, zorder=1)
    ax.plot(x, hi, color=color, ls="--", lw=1.0, alpha=0.7, zorder=1)
    ax.fill_between(x, lo, hi, color=color, alpha=0.06, zorder=0)


def plot_qa(model_name: str, idata, outpath: str) -> None:
    """QA / convergence plot plus an R-hat + ESS summary CSV.

    Saves ArviZ trace plots for the population-level parameters, dumps
    az.summary to ``<outpath without ext>_summary.csv``, and prints any
    R-hat > 1.01, low ESS, or divergences.

    Generated by Claude Code on 2026-06-21.

    Args:
        model_name: One of "shared", "perstar", "broken".
        idata: The corresponding fit.
        outpath: Output PDF path.
    """
    # Drop any population parameter the model did not fit (e.g.
    # sigma_int in the no-intrinsic-scatter variant).
    var_names = [v for v in POP_PARAMS[model_name]
                 if v in idata.posterior.dataset]

    # ArviZ 1.x plot_trace returns a PlotCollection (arviz-plots backend),
    # which exposes its own savefig rather than matplotlib axes.
    pc = az.plot_trace(idata, var_names=var_names)
    try:
        pc.add_title(f"QA: model {model_name}")
    except Exception:  # noqa: BLE001 - title is cosmetic
        pass
    pc.savefig(outpath)
    plt.close("all")

    summ = az.summary(idata, var_names=var_names)
    csv_path = os.path.splitext(outpath)[0] + "_summary.csv"
    summ.to_csv(csv_path)

    # az.summary returns object-dtype columns in ArviZ 1.x; coerce.
    if "r_hat" in summ.columns:
        rhat = pd.to_numeric(summ["r_hat"], errors="coerce")
        bad = list(rhat[rhat > 1.01].index)
        if bad:
            LOG.warning("model %s: R-hat > 1.01 for %s", model_name, bad)
    if "ess_bulk" in summ.columns:
        ess = pd.to_numeric(summ["ess_bulk"], errors="coerce")
        low = list(ess[ess < 400].index)
        if low:
            LOG.warning("model %s: low ESS for %s", model_name, low)

    try:
        div = int(np.asarray(
            idata.sample_stats.dataset["diverging"]).sum())
        LOG.info("model %s: %d divergences", model_name, div)
    except (KeyError, AttributeError):
        pass


def plot_beta_violins(
    idata_shared, idata_perstar, data: Dict, outpath: str
) -> None:
    """Beta violins: 7 columns ("All" + 6 per-star).

    Leftmost column is the Model 1 shared-beta posterior; the remaining
    columns are the Model 2 per-star beta posteriors, sorted by their
    posterior median (largest on the left, smallest on the right).  A
    horizontal reference line marks beta = 0.

    Generated by Claude Code on 2026-06-21.

    Args:
        idata_shared: Model 1 fit.
        idata_perstar: Model 2 fit.
        data: Output of prepare_arrays.
        outpath: Output PDF path.
    """
    set_style("science")
    fig, ax = plt.subplots(figsize=(4, 4))

    beta_all = _flat(idata_shared, "beta")
    beta_s = np.asarray(idata_perstar.posterior.dataset["beta_s"])
    beta_s = beta_s.reshape(-1, beta_s.shape[-1])  # (ndraw, N_s)

    # Sort the per-star columns by descending posterior-median beta.
    order = sorted(
        range(data["N_s"]),
        key=lambda i: np.median(beta_s[:, i]), reverse=True,
    )
    datasets = [beta_all] + [beta_s[:, i] for i in order]
    labels = ["All"] + [data["star_names"][i] for i in order]
    positions = np.arange(len(datasets))

    parts = ax.violinplot(
        datasets, positions=positions, showextrema=False, widths=0.8
    )
    for i, body in enumerate(parts["bodies"]):
        body.set_facecolor("C0" if i == 0 else "C1")
        body.set_alpha(0.6)

    # Median markers match the money-plot style: per-star shapes,
    # white fill, black edge (the aggregate "All" is a solid black
    # circle).  Vertical error bars show the 68% credible interval; the
    # horizontal dimension carries no meaning so it has no error bar.
    for i, d in enumerate(datasets):
        ci = _ci68(d)
        yerr = [[ci["med"] - ci["lo"]], [ci["hi"] - ci["med"]]]
        if i == 0:
            mk, fc = "o", "black"
        else:
            mk = _STAR_MARKERS[order[i - 1] % len(_STAR_MARKERS)]
            fc = "white"
        ax.errorbar(
            positions[i], ci["med"], yerr=yerr, marker=mk,
            markerfacecolor=fc, markeredgecolor="black",
            markeredgewidth=0.8, ecolor="black", color="black",
            markersize=7, elinewidth=0.9, capsize=2, zorder=5,
        )

    ax.axhline(0.0, color="gray", ls="--", lw=0.8)
    ax.set_xticks(positions)
    ax.set_xticklabels(labels, rotation=30, ha="right", fontsize=7)
    ax.set_ylabel(r"$\beta$")
    fig.savefig(outpath, bbox_inches="tight")
    plt.close(fig)
